config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users

  resources :lists do
    get :analytics, on: :member
    get :pie_chart, on: :member
    get :line_chart, on: :member
    resources :list_permissions, only: [:index, :create, :destroy]
    resources :expenses do
      collection do
        get :past_dated
        post :do_past_dated
      end
    end
  end

  resources :shared_lists, only: [:index]
  resources :monthly_bills

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class List < ActiveRecord::Base
  include ExpenseListAnalytics

  belongs_to :user
  has_many :expenses
  has_many :list_permissions

  default_scope { order('created_at DESC') }

  validates :title, presence: true

  def has_permissions?
    list_permissions.count > 0
  end

  def has_budget?
    budget_amount.present?
  end

  def remaining_budget
    return unless has_budget?

    budget_amount - total_amount
  end

  def total_amount
    expenses.map(&:amount).sum
  end

  def max_expense
    expenses.map(&:amount).max
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :show, :destroy, :update, :analytics]
  before_action :authenticate_user!
  before_action :redirect_if_user_is_not_authorized, only: [:edit, :show, :analytics]

  def index
    @lists = current_user.lists.paginate(page: params[:page], per_page: 15)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new list_params
    @list.user_id = current_user.id
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list_expenses = @list.expenses
    @search = @list_expenses.ransack(params[:q])
    @expenses = @search.result.paginate(page: params[:page], per_page: 15)
  end

  def analytics
    @days = params[:days_ago] || (Date.current - @list.expenses.map(&:expense_date).min.to_date).to_i
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

private

  def redirect_if_user_is_not_authorized
    unless authotized_list_user
      not_found
    end
  end

  def authotized_list_user
    if @list.list_permissions.present?
      user_has_permissions = @list.list_permissions.detect do |permission|
        permission.permission_granted_to == current_user.id
      end
    end

    current_user.id == @list.user_id || user_has_permissions
  end

  def set_list
    @list = List.find params[:id]
  end

  def list_params
    params.require(:list).permit :title, :budget_amount
  end

end

app/helpers/lists_helper.rb
module ListsHelper

  def expense_line_chart(num_of_days_ago)
    line_chart [{ name: "Expenses" , data: @list.expense_chart_data(num_of_days_ago)}]
  end

  def category_pie_chart
    pie_chart @list.category_percentage_chart_data.map, width: "auto", library: { tooltip: { valueSuffix: '%' }}
  end

  def show_proper_total
    if !search? || toggle_with_no_search
      "Total Expenses: #{number_to_currency @list.total_amount}"
    elsif search?
      "Total Expenses: #{number_to_currency @search.result.sum(:amount)}"
    else
      "Total Expenses: #{number_to_currency @expenses.sum(:amount)}"
    end
  end

  def list_title(list)
    if list.has_budget?
      "#{list.title} <span>(budget: #{number_to_currency list.budget_amount})</span>".html_safe
    else
      list.title
    end
  end

  def shared_by_name(list)
    User.where(id: list.list_permissions.first.permission_granted_by).first.display_name
  end

  def read_and_write_access?(list)
    permission_access = list.list_permissions.detect do |list_permission|
      list_permission.permission_granted_to == current_user.id
    end

    permission_access.read_and_write_access.present?
  end

  def list_creator(list)
    list.user_id == current_user.id
  end

  private

  def toggle_with_no_search
    search? && params[:q].has_key?(:s) && params[:q].values.count == 1
  end

  def search?
    params[:q].present?
  end

end

app/views/lists/_form.html.haml
.panel-body
  = form_for @list, validate: true do |f|
    = f.label :title
    = f.text_field :title, class: "form-control"
    = f.label "Set your budget "
    %span (optional)
    = f.number_field :budget_amount, class: "form-control", step: 'any'
    %br
    = f.submit 'Submit', class: 'btn btn-primary pull-right'

app/views/lists/_line_chart.html.haml
.line_chart
  .container-fluid
    .h2 Total Expenses per day
    = expense_line_chart(@days)

app/views/lists/_pie_chart.html.haml
.pie_chart
  .container-fluid
    .col-md-5
      .h2 Category Breakdown
      %br
      .cat-data-text
        .h4 Where you've spent the most
        Category:
        %span= @list.most_spent_by_category[:category]
        %br
        Number of expenses:
        %span= @list.most_spent_by_category[:category_count]
        %br
        Total amount:
        %span= number_to_currency @list.most_spent_by_category[:amount]
        - if @list.total_individual_categories_count > 1
          %hr
          .h4 Where you've spent the least
          Category:
          %span= @list.lowest_spent_by_category[:category]
          %br
          Number of expenses:
          %span= @list.lowest_spent_by_category[:category_count]
          %br
          Total amount:
          %span= number_to_currency @list.lowest_spent_by_category[:amount]
    .col-md-7
      %br
      = category_pie_chart
      .pie-chart-text
        *Percentages are based on categories not the amount of expenses
        .br
        or expense total per category.

app/views/lists/analytics.html.haml
#analytics
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        = @list.title
    .panel-body
      .span8.well
        %ul.nav.nav-tabs
          %li.active{:role => "presentation"}
            %a{"aria-controls" => "expenses", "data-toggle" => "tab", :href => "#expenses", :role => "tab"}
              Expenses
              %span
                .badge
                  = @list.expenses.count
          %li
            %a{"aria-controls" => "categories", "data-toggle" => "tab", :href => "#categories", :role => "tab"}
              Categories
              %span
                .badge
                  = @list.total_individual_categories_count
          %li.dropdown.pull-right
            %button.btn.btn-danger.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              %span.caret
            %ul.dropdown-menu
              - if @list.expenses.map(&:expense_date).min <= 7.days.ago
                %li= link_to "1 Week", analytics_list_path(@list, days_ago: 7)
              - if @list.expenses.map(&:expense_date).min <= 14.days.ago
                %li= link_to "2 Weeks", analytics_list_path(@list, days_ago: 14)
              - if @list.expenses.map(&:expense_date).min <= 30.days.ago
                %li= link_to "1 Month", analytics_list_path(@list, days_ago: 30)
              - if @list.expenses.map(&:expense_date).min <= 90.days.ago
                %li= link_to "3 Months", analytics_list_path(@list, days_ago: 90)
              - if @list.expenses.map(&:expense_date).min <= 180.days.ago
                %li= link_to "6 Months", analytics_list_path(@list, days_ago: 180)
              %li= link_to "All Time", analytics_list_path(@list, days_ago: (Date.current - @list.expenses.map(&:expense_date).min.to_date).to_i)
        .tab-content
          #expenses.tab-pane.active{:role => "tabpanel"}
            = render "line_chart"
          #categories.tab-pane{:role => "tabpanel"}
            = render "pie_chart"
      = link_to "Back to list", list_path(@list), class: "btn btn-primary"

app/views/lists/edit.html.haml
#form
  .container
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h2 Edit your Expense List
        = render 'form'

app/views/lists/index.html.haml
-if @lists.empty?
  %h4 Create your first expense list!
  = link_to 'Create a List', new_list_path
-else
  #lists.transitions-enabled
    - @lists.each do |list|
      .box
        .panel.panel-default
          .panel-body.center
            %h3= link_to list.title, list_path(list)
            .time
              %P= "Created #{time_ago_in_words list.created_at} ago"
            .actions.pull-left
              %p= "Total: #{number_to_currency list.total_amount}"
            .pull-right
              = link_to edit_list_path(list) do
                %span.glyphicon.glyphicon-edit
                Edit
              |
              = link_to list, method: :delete, data: { confirm: 'Are you sure?' } do
                %span.glyphicon.glyphicon-trash
                Delete
  = will_paginate @lists
  = link_to 'Create a List', new_list_path, class: 'btn btn-primary pull-right'

app/views/lists/new.html.haml
#form
  .container
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h2 Create a New Expense List
        = render 'form'

app/views/lists/shared_lists.html.haml
-if @shared_lists.empty?
  %h4 No lists have been shared with you at this time.
  = link_to "Back to lists", lists_path
-else
  #lists.transitions-enabled
    - @shared_lists.each do |list|
      .box
        .panel.panel-default
          .panel-body.center
            %h3= link_to list.title, list_path(list)
            .time
              = "shared by: #{shared_by_name(list)}"
              %P= "Created #{time_ago_in_words list.created_at} ago"
            .actions.pull-left
              %p= "Total: #{number_to_currency list.total_amount}"
            .pull-right
              = link_to edit_list_path(list) do
                %span.glyphicon.glyphicon-edit
                Edit
              |
              = link_to list, method: :delete, data: { confirm: 'Are you sure?' } do
                %span.glyphicon.glyphicon-trash
                Delete
  = will_paginate @shared_lists

app/views/lists/show.html.haml
-if params[:q] && @expenses.empty?
  %h4 Sorry, but we could not find any results that matched your criteria. Please try your search again.
  = link_to 'Back', :back
- elsif @expenses.empty?
  %h4= "#{@list.title} does not have any expenses logged at this time."
  = link_to 'Back', :back
  |
  = link_to 'Log Expense', new_list_expense_path(@list)
-else
  - if Feature.active?(:search)
    .col-md-1-pull-right
    = button_tag 'Search', id: 'search-button', class: 'btn btn-default' do
      %span.glyphicon.glyphicon-search
  = render 'shared/expense_search'
  = render 'shared/expenses'