config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users

  resources :lists do
    get :analytics, on: :member
    get :pie_chart, on: :member
    get :line_chart, on: :member
    resources :list_permissions, only: [:index, :create, :destroy]
    resources :expenses do
      collection do
        get :past_dated
        post :do_past_dated
      end
    end
  end

  resources :shared_lists, only: [:index]
  resources :monthly_bills

end

app/views/shared/_expense_search.html.haml
#search-form
  = search_form_for [@list, @search] do |f|
    #search-bar
      .container
        .row
          .panel.panel-default
            .panel-body
              - if Feature.active?(:invite_user)
                .col-md-2
                  = f.search_field :expense_date_date_equals, class: 'form-control', placeholder: 'Date (mm/dd/yyyy)'
              - else
                .col-md-3
                  = f.search_field :expense_date_date_equals, class: 'form-control', placeholder: 'Date (mm/dd/yyyy)'
              - if Feature.active?(:invite_user)
                .col-md-2
                  = f.text_field :user_display_name_cont, class: 'form-control', placeholder: 'Person'
              .col-md-3
                = f.text_field :category_name_or_sub_category_name_or_name_cont, class: 'form-control', placeholder: 'Category or Expense'
              .col-md-3
                = f.text_field :amount_gteq, class: 'form-control', placeholder: 'Amount (greater than)'
              - if Feature.active?(:invite_user)
                .col-md-2
                  = f.submit 'Search', id: 'search-submit', class: 'form-control btn-info'
              - else
                .col-md-3
                  = f.submit 'Search', id: 'search-submit', class: 'form-control btn-info'

app/views/shared/_expenses.html.haml
#list-expenses
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        = list_title(@list)
        - if list_creator(@list)
          .add-expense.pull-right
            = link_to list_list_permissions_path(@list), "data-no-turbolink" => "true" do
              %span.glyphicon.glyphicon-plus
    .panel-body
      .panel.panel-default
        .table-responsive
          %table.table.table-bordered
            %tr
              %th= sort_link @search, :expense_date, 'Date'
              - if Feature.active?(:invite_user)
                %th= sort_link @search, :user_display_name, 'Person'
              %th= sort_link @search, :category_id
              %th  Expense
              %th= sort_link @search, :amount
              %th  Description
              - if list_creator(@list) || read_and_write_access?(@list)
                %th  Edit/Delete
            - @expenses.each do |expense|
              %tr
                %td= expense.expense_date.strftime("%B %d, %Y")
                - if Feature.active?(:invite_user)
                  %td= expense.user.display_name
                -if expense.category
                  %td= expense.category.name
                -else
                  %td= 'Other'
                -if expense.sub_category && expense.category.id != 15
                  %td= expense.sub_category.name
                -else
                  %td= expense.name
                %td= number_to_currency expense.amount
                %td= expense.description.present? ? (auto_link expense.description) : 'N/A'
                - if list_creator(expense.list) || read_and_write_access?(@list)
                  %td
                    = link_to 'Edit', edit_list_expense_path(@list, expense)
                    |
                    = link_to 'Delete', list_expense_path(@list, expense), method: :delete, data: {confirm: "Are you sure?"}
      .well.well-sm
        .budget_remaining
          - if @list.has_budget?
            - if @list.remaining_budget >= 0
              = "Remaining: #{number_to_currency @list.remaining_budget}"
            - elsif @list.remaining_budget < 0
              %span= "Over Budget: #{number_to_currency @list.remaining_budget}"
        .total
          = show_proper_total
          .pull-right
            %span.glyphicon.glyphicon-stats
            = link_to 'Analytics', analytics_list_path(@list)
      = will_paginate @expenses
      - if list_creator(@list) || read_and_write_access?(@list)
        = link_to 'Log Expense', new_list_expense_path(@list), class: 'btn btn-primary pull-right'