config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users

  resources :lists do
    get :analytics, on: :member
    get :pie_chart, on: :member
    get :line_chart, on: :member
    resources :list_permissions, only: [:index, :create, :destroy]
    resources :expenses do
      collection do
        get :past_dated
        post :do_past_dated
      end
    end
  end

  resources :shared_lists, only: [:index]
  resources :monthly_bills

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to lists_path
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_favicon.html.haml
- %w(76 120 152 180).each do |size|
  = favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}"

app/views/welcome/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    - if user_signed_in?
      = link_to 'Expense Pro', lists_path, class: "navbar-brand"
    -else
      = link_to 'Expense Pro', root_path, class: "navbar-brand"
    %ul.nav.pull-right
      - if user_signed_in? && mobile_device?
        %li.dropdown.pull-right
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :style => "color:#777; margin-top: 5px;"}
            %span.glyphicon.glyphicon-user
            %b.caret
          %ul.dropdown-menu
            .dropdown-header Monthly Bills
            %li= link_to "Add a Bill", new_monthly_bill_path
            %li= link_to "View Monthly Bills", monthly_bills_path
            .dropdown-header Expense Lists
            %li= link_to "Add a New List", new_list_path
            %li= link_to "My Lists", lists_path
            %li= link_to "Shared Lists", shared_lists_path
            .dropdown-header= "#{current_user.display_name}"
            %li= link_to "Edit Account", edit_user_registration_path
            - if Feature.active?(:invite_user, current_user)
              %li= link_to "Send Invite", new_user_invitation_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - elsif user_signed_in?
        .btn-group
          %button.btn.btn-danger.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
            Expense Lists
          %ul.dropdown-menu
            %li= link_to "Add a New List", new_list_path
            %li= link_to "My Lists", lists_path
            %li= link_to "Shared Lists", shared_lists_path
        .btn-group
          %button.btn.btn-danger.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
            Monthly Bills
          %ul.dropdown-menu
            %li= link_to "Add a Bill", new_monthly_bill_path
            %li= link_to "View Monthly Bills", monthly_bills_path
        .btn-group
          %button.btn.btn-danger.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
            = "#{current_user.display_name}"
          %ul.dropdown-menu
            %li= link_to "Edit Account", edit_user_registration_path
            - if Feature.active?(:invite_user, current_user)
              %li= link_to "Send Invite", new_user_invitation_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/welcome/index.html.haml
.jumbotron
  .container
    .h1 Expense Pro
    %p A simple solution for tracking your expenses.
    = link_to 'Sign in', user_session_path, class: 'btn btn-primary btn-lg'
    OR
    = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg'