config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users

  resources :lists do
    get :analytics, on: :member
    get :pie_chart, on: :member
    get :line_chart, on: :member
    resources :list_permissions, only: [:index, :create, :destroy]
    resources :expenses do
      collection do
        get :past_dated
        post :do_past_dated
      end
    end
  end

  resources :shared_lists, only: [:index]
  resources :monthly_bills

end

app/controllers/shared_lists_controller.rb
class SharedListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @shared_lists = shared_lists.paginate(page: params[:page], per_page: 15)
  end

private

  def permissions_granted_for_current_user
    ListPermission.where(permission_granted_to: current_user.id)
  end

  def shared_lists
    lists = []

    permissions_granted_for_current_user.each do |permissions|
      list = permissions.list
      lists << list
    end

    lists
  end

end

app/views/shared_lists/index.html.haml
-if @shared_lists.empty?
  %h4 No lists have been shared with you at this time.
  = link_to "Back to lists", lists_path
-else
  #lists.transitions-enabled
    - @shared_lists.each do |list|
      .box
        .panel.panel-default
          .panel-body.center
            %h3= link_to list.title, list_path(list)
            .time
              = "shared by: #{shared_by_name(list)}"
              %P= "Created #{time_ago_in_words list.created_at} ago"
            .actions.pull-left
              %p= "Total: #{number_to_currency list.total_amount}"
            - if list_creator(list) || read_and_write_access?(list)
              .pull-right
                = link_to edit_list_path(list) do
                  %span.glyphicon.glyphicon-edit
                  Edit
                |
                = link_to list, method: :delete, data: { confirm: 'Are you sure?' } do
                  %span.glyphicon.glyphicon-trash
                  Delete
  = will_paginate @shared_lists